### ISSUE TITLE
Stand-alone PE cleaning does not appear to be working

### ISSUE THREAD

**Issue by bricesarver** [msettles/expHTS#54]
I think this bug was introduced relative to the last time I tried some cleaning, because I cannot get folders with just PE data to be processed.

I previously processed some data made up of two PE FASTQ files and had no issues. This looks like it was over a month ago. I must have updated things in the interim as part of general server maintenance.

I can no longer get the data processed above to clean. It completes but does nothing, as described in Issue 52. Additionally, when I try to pass various flags/arguments to it, I generally get the same thing EXCEPT for the --skip-duplicates flag, which throws an index error:

```
super_deduper found
sickle found
flash2 found
bowtie2 found
scythe found
___ PE COMMANDS ___
python /usr/local/lib/python2.7/dist-packages/expHTS-1.0.1.dev2-py2.7-linux-x86_64.egg/expHTS/cleanupWrapper.py  <(flash2 -Ti <(sickle pe -c <(super_deduper -i <(python /usr/local/lib/python2.7/dist-packages/expHTS-1.0.1.dev2-py2.7-linux-x86_64.egg/expHTS/extract_unmapped_reads.py  <(python /usr/local/lib/python2.7/dist-packages/expHTS-1.0.1.dev2-py2.7-linux-x86_64.egg/expHTS/screen.py -1 /scratch/1/brice/coding_expression/capture_data/test/00-RawData/22MO/22MO_R1.fastq.gz  -2 /scratch/1/brice/coding_expression/capture_data/test/00-RawData/22MO/22MO_R2.fastq.gz   -t 5 2>/dev/null)   -o stdout 2>02-Cleaned/22MO/PE_filter_info.log)  -p stdout 2>02-Cleaned/22MO/PE_deduper_info.log)   -m stdout -s /dev/null -t sanger -T  2>02-Cleaned/22MO/PE_sickle_info.log)   -M 700 --allow-outies -o 22MO -d 02-Cleaned/22MO -To -c  2>02-Cleaned/22MO/flash_info.log)   0 0 25 02-Cleaned/22MO/22MO
02-Cleaned/22MO
Seconds: 0.0303189754486
Total amount of seconds to run all samples
Seconds: 0.0303189754486

```

And, with the flag, after blowing away the folder:

```
super_deduper found
sickle found
flash2 found
bowtie2 found
scythe found
___ PE COMMANDS ___
python /usr/local/lib/python2.7/dist-packages/expHTS-1.0.1.dev2-py2.7-linux-x86_64.egg/expHTS/cleanupWrapper.py  <(flash2 -Ti <(sickle pe -c <(python /usr/local/lib/python2.7/dist-packages/expHTS-1.0.1.dev2-py2.7-linux-x86_64.egg/expHTS/extract_unmapped_reads.py  <(python /usr/local/lib/python2.7/dist-packages/expHTS-1.0.1.dev2-py2.7-linux-x86_64.egg/expHTS/screen.py -1 /scratch/1/brice/coding_expression/capture_data/test/00-RawData/22MO/22MO_R1.fastq.gz  -2 /scratch/1/brice/coding_expression/capture_data/test/00-RawData/22MO/22MO_R2.fastq.gz   -t 5 2>/dev/null)   -o stdout 2>02-Cleaned/22MO/PE_filter_info.log)   -m stdout -s /dev/null -t sanger -T  2>02-Cleaned/22MO/PE_sickle_info.log)   -M 700 --allow-outies -o 22MO -d 02-Cleaned/22MO -To -c  2>02-Cleaned/22MO/flash_info.log)   0 0 25 02-Cleaned/22MO/22MO
02-Cleaned/22MO
Seconds: 1.76817893982
Traceback (most recent call last):
  File "/usr/local/bin/expHTS", line 9, in <module>
    load_entry_point('expHTS==1.0.1.dev2', 'console_scripts', 'expHTS')()
  File "/usr/local/lib/python2.7/dist-packages/expHTS-1.0.1.dev2-py2.7-linux-x86_64.egg/expHTS/__init__.py", line 18, in main
    expHTS.main()
  File "/usr/local/lib/python2.7/dist-packages/expHTS-1.0.1.dev2-py2.7-linux-x86_64.egg/expHTS/expHTS.py", line 167, in main
    commands[args.command].execute(args)
  File "/usr/local/lib/python2.7/dist-packages/expHTS-1.0.1.dev2-py2.7-linux-x86_64.egg/expHTS/preprocessCMD.py", line 136, in execute
    logFiles.append(parseOut(key[1], key[1].split("/")[-1]))
  File "/usr/local/lib/python2.7/dist-packages/expHTS-1.0.1.dev2-py2.7-linux-x86_64.egg/expHTS/parse_files.py", line 257, in parseOut
    printToFile(os.path.join(base, sample + "_SummaryStats.log"), header, data)
  File "/usr/local/lib/python2.7/dist-packages/expHTS-1.0.1.dev2-py2.7-linux-x86_64.egg/expHTS/parse_files.py", line 235, in printToFile
    if '\t'.join(map(str, data))[-1] != '\n':
IndexError: string index out of range
```

I spent several hours trying to track this down (thought I was going crazy because what should be a straightforward process was now broken with seemingly no cause). Again, note that this proceeds fine on SE reads. Additionally, I was monitoring server resource usage, and things appear to exit uncleanly; there are Perl, Python, gzip, and Bowtie2 calls that hang around for a while (~ 1m) seemingly doing nothing in a sleep or deferred state before ultimately being resolved.

**Comment by bricesarver** [comment]
Update: Everything was up to date, minus an update to Scythe. I rebuilt everything from scratch anyway. It appears to be working now for no clear reason. I am now wondering whether other processes might have been interfering with stuff. There were a couple high I/O apps being run by some people at the time; should this have any affect on the stream processing of expHTS if some of the individual calls' (Perl/Python/gzip/etc.) processes were put into a sleep state or deferred? I'm wondering if one step is put on hold whether or not it proceeds to the next one and terminates the call for that sample. Doesn't seem likely, but perhaps something to look into.

**Comment by bricesarver** [comment]
I think this is still an issue. Something wonky is going on. If I have a folder with just PE data, expHTS will run but only in SE mode.

**Comment by bricesarver** [comment]
I'll close this and raise a bigger issue with versioning info.
